version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.3.0"

    steps:
      - checkout

      # Build the app and run tests
      - run:
          name: Install
          command: bundle install

      - run:
          name: Build
          command: bundle exec fastlane ggwp